version: "3"
services:
  sangwondb:
    container_name: sangwondb
    image: postgres:latest
    ports:
      - "5436:5432"
    env_file:
      - .env
  redis:
    container_name: sangwon_redis
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - 6379:6379

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=sangwon
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=sangwon


